### PR TITLE
Bump glslify, fix deps

### PR DESCRIPTION
**Pull request by dy**
https://github.com/plotly/plotly.js/issues/2321 + makes sure example is runnable

### CODE REVIEW

**Comment by etpinard** [comment]
:dancer:

**Comment by dy** [comment]
@etpinard @monfera can you please do `npm publish` here or grant me permission `npm owner add dfcreative gl-pointcloud2d`

**Comment by etpinard** [comment]
I don't have publish rights for gl-pointcloud2d unfortunately. So it's up to @monfera (no rush though :smile: )

**Comment by monfera** [comment]
@dfcreative @etpinard thanks for the note, I just added both of you, tell me if it doesn't work out.
image

Have we a codepen similar to [this](https://codepen.io/monfera/pen/BLjJVZ) that shows the (by client requirement, low) initialization and update latency? I just re-checked it, it used to be 25-30FPS but now only around half of that, not sure if it's due to possibly slower browser / OS versions. We must be able to do a redraw cycle in <100ms so we're still good; I'm sure the new thing is as good or is an improvement.

**Comment by etpinard** [comment]
@monfera are you suggesting that bumping the `glslify` version slowed down `pointcloud`?

**Comment by monfera** [comment]
@etpinard no, because that wouldn't have changed the shader code; there might have been some general or WebGL specific slowdown in browsers. Fixes for things like Meltdown, Spectre or bugs may influence performance.

**Comment by etpinard** [comment]
Ah nice. Good to know. Thanks for pointing this out!

**Pull request merged**
